wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1656594528
    t:
      1:
      - 55
      3:
      - 16
      4: 3.7.12
      5: 0.12.16
      8:
      - 1
      - 5
run:
  desc: null
  value: test
